### ISSUE TITLE
Proposta per pedalar

### ISSUE THREAD

**Issue by twein** [twein/divendres_toni#3]
Hauríem de pedalar avui, no? El temps no pinta gaire bé.

Feu un fitxer al meu repositori amb la teva opinió.

**Comment by Josep-Pages** [comment]
To be determined...... a bit of a hectic schedule: he d'anar a ca'ls oncles a mirar com estan.

**Comment by Josep-Pages** [comment]
## recepta de coses per determinar.
#1 acabar curset de git
## acabar curset de mindfulness de 12 a 14
## Anar a ca'ls oncles un momentet a Girona
## Tornar a Sant Gregori a mirar Martí si dina (cap a les 3)
## Fer bici ?????

**Comment by Josep-Pages** [comment]
Em temo que hauré de fer un altre Sant Grau... si no plou

**Comment by Josep-Pages** [comment]
Ja quedarem!
